export const DIRECTORY = {
    REQUEST: 'DIRECTORY_REQUEST',
    SUCCESS: 'DIRECTORY_REQUEST_SUCCESS',
    FAILURE: 'DIRECTORY_REQUEST_FAILURE'
}

export const FILE = {
    REQUEST: 'FILE_REQUEST',
    SUCCESS: 'FILE_REQUEST_SUCCESS',
    FAILURE: 'FILE_REQUEST_FAILURE'
}

export const FETCHING = 'FETCHING';