export const DIRECTORY = {
    REQUEST: 'DIRECTORY_REQUEST',
    SUCCESS: 'DIRECTORY_REQUEST_SUCCESS',
    FAILURE: 'DIRECTORY_REQUEST_FAILURE'
}

export const SUBDIRECTORY = {
    REQUEST: 'SUBDIRECTORY_REQUEST',
    SUCCESS: 'SUBDIRECTORY_REQUEST_SUCCESS',
    FAILURE: 'SUBDIRECTORY_REQUEST_FAILURE'
}

export const FILE = {
    REQUEST: 'FILE_REQUEST',
    SUCCESS: 'FILE_REQUEST_SUCCESS',
    FAILURE: 'FILE_REQUEST_FAILURE'
}

export const LOGIN = {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE'
}

export const FETCHING = 'FETCHING';