export const DIRECTORY = {
    REQUEST: 'DIRECTORY_REQUEST',
    SUCCESS: 'DIRECTORY_REQUEST_SUCCESS',
    FAILURE: 'DIRECTORY_REQUEST_FAILURE'
}

export const SUBDIRECTORY = {
    REQUEST: 'SUBDIRECTORY_REQUEST',
    SUCCESS: 'SUBDIRECTORY_REQUEST_SUCCESS',
    FAILURE: 'SUBDIRECTORY_REQUEST_FAILURE'
}

export const FILE = {
    REQUEST: 'FILE_REQUEST',
    SUCCESS: 'FILE_REQUEST_SUCCESS',
    FAILURE: 'FILE_REQUEST_FAILURE'
}

export const NOTES = {
    REQUEST: 'NOTES_REQUEST',
    SUCCESS: 'NOTES_REQUEST_SUCCESS',
    FAILURE: 'NOTES_REQUEST_FAILURE'
}

export const NOTE = {
    ADD: {
        REQUEST: 'NOTE_ADD_REQUEST',
        SUCCESS: 'NOTE_ADD_SUCCESS',
        FAILURE: 'NOTE_ADD_FAILURE'
    }
}

export const LOGIN = {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE',
    RENEW: {
        REQUEST: 'LOGIN_RENEW_REQUEST',
        SUCCESS: 'LOGIN_RENEW_SUCCESS',
        FAILURE: 'LOGIN_RENEW_FAILURE'
    },
    UPDATE: 'LOGIN_UPDATE'
}
export const LANG = {
    SET: 'LANG_SET'
}

export const FETCHING = 'FETCHING';